cargo-features = ["edition2024"]

[package]
name = "dinocore"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"

[lib]
name = "dinocore"
path = "src/lib.rs"

[[bin]]
name = "dino"
path = "src/main.rs"
